### ISSUE TITLE
Java Script / Haxball-Headless Help

### ISSUE THREAD

**Issue by IvanBre** [Raamyy/The-Pharon#1]
Hello everyone! 

I have programmed VPS Automated Room, and i need AntiKick function

If someone can help me i'll be grateful

Thanks !

**Comment by Raamyy** [comment]
Hello @IvanBre ,

I think the best place to post this issue will be at the [official haxball repo](https://github.com/haxball/haxball-issues/). So you will get help from all of the community.

Anyways *preventing* kick is not possible with the current API, So you can't prevent someone to be kicked. 

For example you can kick or ban the player who kicked somebody, But as I said you can't prevent him to be kicked.

Let me know if you have more inquiries.

**Comment by IvanBre** [comment]
Hey @Raamyy ,

Thank you for replay, I'll do that

I hope you enjoy in the day :)
